version: '2'

services:

  redmine:
    image: dina/redmine:v0.1
    environment:
      - VIRTUAL_HOST=support.dina-web.net
      - REDMINE_DB_MYSQL=mariadb_redmine
      - REDMINE_DB_PASSWORD=secr3t
    volumes:
      - ./redmine-files:/usr/src/redmine/files
    links:
      - mariadb:mariadb_redmine

  mariadb:
    image: mariadb:10.1
    environment:
      MYSQL_DATABASE: redmine
      MYSQL_ROOT_PASSWORD: secr3t
    volumes:
      - ./redminedb-init.d:/docker-entrypoint-initdb.
